feat: add support for planet selection via CLI
South-Paw/salien-script-js pull request #18
Opened 2018-06-25 01:00 UTC by NicholasCostanzo

Adds feature to pass `-p <planet_id>` or `--planet <planet_id>` in CLI.
Script will attempt to use the planet if its available, otherwise the default behavior will be used.

2018-06-25 03:20 UTC, resir014 requested changes
Thank you so much for this, you're a legend! ❤️ 

I've run your branch as a test and I've found one minor issue. Once fixed, this is good to merge!

2018-06-25 03:20 UTC, resir014 commented on src/index.js
> +          `>> Selected planet ${chalk.yellow(this.planet)} not available. Slecting next available planet...`,
Planet name here shows up on the log as `null` if no `--planet` flag is set. Consider setting up a guard to check if we actually set a `--planet`

Also, typo: `Slecting` -> `Selecting`

![image](https://user-images.githubusercontent.com/5663877/41828786-623b0904-7861-11e8-9938-7c5b93c3ce5e.png)

2018-06-25 14:07 UTC, resir014 approved these changes
LGTM, thanks for this!

2018-06-25 14:07 UTC, merged

2018-06-25 14:11 UTC, NicholasCostanzo commented
Happy to help :)

2018-06-27 06:04 UTC, resir014 commented
Hey @NicholasCostanzo, sorry but we'll have to revert this PR for now since some users have reported issues with it.

We're still investigating, but we might be able to bring this back after [our rewrite](https://github.com/South-Paw/salien-script-js/pull/19) is complete.

Thanks for your help though!